musical_keys = {
    "C": ["C", "Dm", "Em", "F", "G", "Am", "Bdim"],
    "D": ["D", "Em", "F#m", "G", "A", "Bm", "C#dim"],
    "E": ["E", "F#m", "G#m", "A", "B", "C#m", "D#dim"],
    "F": ["F", "Gm", "Am", "Bb", "C", "Dm", "Edim"],
    "G": ["G", "Am", "Bm", "C", "D", "Em", "F#dim"],
    "A": ["A", "Bm", "C#m", "D", "E", "F#m", "G#dim"],
    "B": ["B", "C#m", "D#m", "E", "F#", "G#m", "A#dim"],
    "Cm": ["Cm", "Ddim", "Eb", "Fm", "Gm", "Ab", "Bb"],
    "Dm": ["Dm", "Edim", "F", "Gm", "Am", "Bbm", "C"],
    "Em": ["Em", "F#dim", "G", "Am", "Bm", "C", "D"],
    "Fm": ["Fm", "Gdim", "Ab", "Bbm", "Cm", "Db", "Eb"],
    "Gm": ["Gm", "Adim", "Bb", "Cm", "Dm", "Eb", "F"],
    "Am": ["Am", "Bdim", "C", "Dm", "Em", "F", "G"],
    "Bm": ["Bm", "C#dim", "D", "Em", "F#m", "G", "A"],
}
